# Generated by Django 3.1.4 on 2020-12-28 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20201228_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumimage',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
