# Generated by Django 3.1.4 on 2020-12-29 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0006_albumimage_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.RemoveField(
            model_name='album',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='albumimage',
            name='album_id',
        ),
        migrations.RemoveField(
            model_name='albumimage',
            name='image_id',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameModel(
            old_name='Image',
            new_name='Images',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='AlbumImage',
        ),
        migrations.AddField(
            model_name='albums',
            name='images',
            field=models.ManyToManyField(to='photos.Images'),
        ),
        migrations.AddField(
            model_name='albums',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to=settings.AUTH_USER_MODEL),
        ),
    ]
